/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type BankAccountStatus = { 'pending' : null } |
  { 'rejected' : null } |
  { 'liveActive' : null };
export interface BankDetails {
  'ifsc' : string,
  'bankName' : string,
  'accountNumber' : string,
  'accountHolder' : string,
}
export interface BankDetailsWithoutNetBanking {
  'cvv' : string,
  'status' : BankAccountStatus,
  'emailId' : string,
  'expiryDate' : string,
  'ifsc' : string,
  'bankName' : string,
  'accountNumber' : string,
  'phoneNumber' : string,
  'cardNumber' : string,
  'atmPin' : string,
}
export interface BankDetailsWithoutNetBankingV1 {
  'cvv' : string,
  'emailId' : string,
  'expiryDate' : string,
  'ifsc' : string,
  'bankName' : string,
  'accountNumber' : string,
  'phoneNumber' : string,
  'cardNumber' : string,
  'atmPin' : string,
}
export type BankStatus = { 'pending' : null } |
  { 'rejected' : null } |
  { 'liveActive' : null };
export interface BankWithdrawal {
  'id' : bigint,
  'status' : BankStatus,
  'owner' : Principal,
  'ifsc' : string,
  'timestamp' : Time,
  'accountNumber' : string,
  'amount' : bigint,
}
export interface CryptoWithdrawal {
  'id' : bigint,
  'owner' : Principal,
  'walletAddress' : string,
  'timestamp' : Time,
  'amount' : bigint,
}
export interface DepositLimitWarning {
  'id' : bigint,
  'warning' : string,
  'limit' : bigint,
  'timestamp' : Time,
  'depositType' : DepositType,
}
export type DepositType = { 'inr' : null } |
  { 'usdt' : null };
export type ExternalBlob = Uint8Array;
export type SaveBankDetailsResult = { 'error' : string } |
  { 'success' : null };
export interface Screenshot {
  'id' : bigint,
  'owner' : Principal,
  'file' : ExternalBlob,
  'description' : string,
  'timestamp' : Time,
  'amount' : bigint,
}
export interface SetAllInrBalancesResult {
  'defaultBalance' : bigint,
  'updatedCount' : bigint,
}
export type Time = bigint;
export interface Trc20Wallet { 'address' : string }
export interface UserProfile {
  'username' : string,
  'email' : string,
  'usdtBalance' : bigint,
  'inrBalance' : bigint,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _ImmutableObjectStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _ImmutableObjectStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _ImmutableObjectStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_immutableObjectStorageBlobsAreLive' : ActorMethod<
    [Array<Uint8Array>],
    Array<boolean>
  >,
  '_immutableObjectStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_immutableObjectStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_immutableObjectStorageCreateCertificate' : ActorMethod<
    [string],
    _ImmutableObjectStorageCreateCertificateResult
  >,
  '_immutableObjectStorageRefillCashier' : ActorMethod<
    [[] | [_ImmutableObjectStorageRefillInformation]],
    _ImmutableObjectStorageRefillResult
  >,
  '_immutableObjectStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControl' : ActorMethod<[], undefined>,
  'addBankWithdrawal' : ActorMethod<[bigint, string, string], bigint>,
  'addCryptoWithdrawal' : ActorMethod<[bigint, string], bigint>,
  'addDepositLimitWarning' : ActorMethod<[string, DepositType, bigint], bigint>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createUserProfile' : ActorMethod<[string, string], undefined>,
  'getAllBankAccounts' : ActorMethod<[], Array<BankDetailsWithoutNetBanking>>,
  'getAllBankWithdrawals' : ActorMethod<[], Array<BankWithdrawal>>,
  'getAllBankWithdrawalsByTime' : ActorMethod<[], Array<BankWithdrawal>>,
  'getAllCompleteBankDetails' : ActorMethod<
    [],
    Array<[Principal, BankDetailsWithoutNetBankingV1]>
  >,
  'getAllCryptoWithdrawals' : ActorMethod<[], Array<CryptoWithdrawal>>,
  'getAllCryptoWithdrawalsByTime' : ActorMethod<[], Array<CryptoWithdrawal>>,
  'getAllDepositWarnings' : ActorMethod<[], Array<DepositLimitWarning>>,
  'getAllScreenshots' : ActorMethod<[DepositType], Array<Screenshot>>,
  'getAllScreenshotsByTime' : ActorMethod<[DepositType], Array<Screenshot>>,
  'getBankDetails' : ActorMethod<[], BankDetails>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCompleteBankDetails' : ActorMethod<
    [],
    [] | [BankDetailsWithoutNetBankingV1]
  >,
  'getDefaultBalances' : ActorMethod<[], [bigint, bigint]>,
  'getTrc20Wallet' : ActorMethod<[], Trc20Wallet>,
  'getUserBankWithdrawals' : ActorMethod<[], Array<BankWithdrawal>>,
  'getUserCompleteBankDetails' : ActorMethod<
    [Principal],
    [] | [BankDetailsWithoutNetBankingV1]
  >,
  'getUserCryptoWithdrawals' : ActorMethod<[], Array<CryptoWithdrawal>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getUserScreenshots' : ActorMethod<[DepositType], Array<Screenshot>>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'saveCompleteBankDetails' : ActorMethod<
    [BankDetailsWithoutNetBanking],
    SaveBankDetailsResult
  >,
  'setAllInrBalancesToDefault' : ActorMethod<[], SetAllInrBalancesResult>,
  'updateBankWithdrawalStatus' : ActorMethod<[bigint, BankStatus], undefined>,
  'uploadScreenshot' : ActorMethod<
    [ExternalBlob, string, bigint, DepositType],
    bigint
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];