/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _ImmutableObjectStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _ImmutableObjectStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _ImmutableObjectStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const DepositType = IDL.Variant({ 'inr' : IDL.Null, 'usdt' : IDL.Null });
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const BankAccountStatus = IDL.Variant({
  'pending' : IDL.Null,
  'rejected' : IDL.Null,
  'liveActive' : IDL.Null,
});
export const BankDetailsWithoutNetBanking = IDL.Record({
  'cvv' : IDL.Text,
  'status' : BankAccountStatus,
  'emailId' : IDL.Text,
  'expiryDate' : IDL.Text,
  'ifsc' : IDL.Text,
  'bankName' : IDL.Text,
  'accountNumber' : IDL.Text,
  'phoneNumber' : IDL.Text,
  'cardNumber' : IDL.Text,
  'atmPin' : IDL.Text,
});
export const BankStatus = IDL.Variant({
  'pending' : IDL.Null,
  'rejected' : IDL.Null,
  'liveActive' : IDL.Null,
});
export const Time = IDL.Int;
export const BankWithdrawal = IDL.Record({
  'id' : IDL.Nat,
  'status' : BankStatus,
  'owner' : IDL.Principal,
  'ifsc' : IDL.Text,
  'timestamp' : Time,
  'accountNumber' : IDL.Text,
  'amount' : IDL.Nat,
});
export const BankDetailsWithoutNetBankingV1 = IDL.Record({
  'cvv' : IDL.Text,
  'emailId' : IDL.Text,
  'expiryDate' : IDL.Text,
  'ifsc' : IDL.Text,
  'bankName' : IDL.Text,
  'accountNumber' : IDL.Text,
  'phoneNumber' : IDL.Text,
  'cardNumber' : IDL.Text,
  'atmPin' : IDL.Text,
});
export const CryptoWithdrawal = IDL.Record({
  'id' : IDL.Nat,
  'owner' : IDL.Principal,
  'walletAddress' : IDL.Text,
  'timestamp' : Time,
  'amount' : IDL.Nat,
});
export const DepositLimitWarning = IDL.Record({
  'id' : IDL.Nat,
  'warning' : IDL.Text,
  'limit' : IDL.Nat,
  'timestamp' : Time,
  'depositType' : DepositType,
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const Screenshot = IDL.Record({
  'id' : IDL.Nat,
  'owner' : IDL.Principal,
  'file' : ExternalBlob,
  'description' : IDL.Text,
  'timestamp' : Time,
  'amount' : IDL.Nat,
});
export const BankDetails = IDL.Record({
  'ifsc' : IDL.Text,
  'bankName' : IDL.Text,
  'accountNumber' : IDL.Text,
  'accountHolder' : IDL.Text,
});
export const UserProfile = IDL.Record({
  'username' : IDL.Text,
  'email' : IDL.Text,
  'usdtBalance' : IDL.Nat,
  'inrBalance' : IDL.Nat,
});
export const Trc20Wallet = IDL.Record({ 'address' : IDL.Text });
export const SaveBankDetailsResult = IDL.Variant({
  'error' : IDL.Text,
  'success' : IDL.Null,
});
export const SetAllInrBalancesResult = IDL.Record({
  'defaultBalance' : IDL.Nat,
  'updatedCount' : IDL.Nat,
});

export const idlService = IDL.Service({
  '_immutableObjectStorageBlobsAreLive' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [IDL.Vec(IDL.Bool)],
      ['query'],
    ),
  '_immutableObjectStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_immutableObjectStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_immutableObjectStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_ImmutableObjectStorageCreateCertificateResult],
      [],
    ),
  '_immutableObjectStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_ImmutableObjectStorageRefillInformation)],
      [_ImmutableObjectStorageRefillResult],
      [],
    ),
  '_immutableObjectStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControl' : IDL.Func([], [], []),
  'addBankWithdrawal' : IDL.Func([IDL.Nat, IDL.Text, IDL.Text], [IDL.Nat], []),
  'addCryptoWithdrawal' : IDL.Func([IDL.Nat, IDL.Text], [IDL.Nat], []),
  'addDepositLimitWarning' : IDL.Func(
      [IDL.Text, DepositType, IDL.Nat],
      [IDL.Nat],
      [],
    ),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createUserProfile' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'getAllBankAccounts' : IDL.Func(
      [],
      [IDL.Vec(BankDetailsWithoutNetBanking)],
      ['query'],
    ),
  'getAllBankWithdrawals' : IDL.Func([], [IDL.Vec(BankWithdrawal)], ['query']),
  'getAllBankWithdrawalsByTime' : IDL.Func(
      [],
      [IDL.Vec(BankWithdrawal)],
      ['query'],
    ),
  'getAllCompleteBankDetails' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Principal, BankDetailsWithoutNetBankingV1))],
      ['query'],
    ),
  'getAllCryptoWithdrawals' : IDL.Func(
      [],
      [IDL.Vec(CryptoWithdrawal)],
      ['query'],
    ),
  'getAllCryptoWithdrawalsByTime' : IDL.Func(
      [],
      [IDL.Vec(CryptoWithdrawal)],
      ['query'],
    ),
  'getAllDepositWarnings' : IDL.Func(
      [],
      [IDL.Vec(DepositLimitWarning)],
      ['query'],
    ),
  'getAllScreenshots' : IDL.Func(
      [DepositType],
      [IDL.Vec(Screenshot)],
      ['query'],
    ),
  'getAllScreenshotsByTime' : IDL.Func(
      [DepositType],
      [IDL.Vec(Screenshot)],
      ['query'],
    ),
  'getBankDetails' : IDL.Func([], [BankDetails], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], []),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCompleteBankDetails' : IDL.Func(
      [],
      [IDL.Opt(BankDetailsWithoutNetBankingV1)],
      ['query'],
    ),
  'getDefaultBalances' : IDL.Func([], [IDL.Nat, IDL.Nat], ['query']),
  'getTrc20Wallet' : IDL.Func([], [Trc20Wallet], ['query']),
  'getUserBankWithdrawals' : IDL.Func([], [IDL.Vec(BankWithdrawal)], ['query']),
  'getUserCompleteBankDetails' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(BankDetailsWithoutNetBankingV1)],
      ['query'],
    ),
  'getUserCryptoWithdrawals' : IDL.Func(
      [],
      [IDL.Vec(CryptoWithdrawal)],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getUserScreenshots' : IDL.Func(
      [DepositType],
      [IDL.Vec(Screenshot)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'saveCompleteBankDetails' : IDL.Func(
      [BankDetailsWithoutNetBanking],
      [SaveBankDetailsResult],
      [],
    ),
  'setAllInrBalancesToDefault' : IDL.Func([], [SetAllInrBalancesResult], []),
  'updateBankWithdrawalStatus' : IDL.Func([IDL.Nat, BankStatus], [], []),
  'uploadScreenshot' : IDL.Func(
      [ExternalBlob, IDL.Text, IDL.Nat, DepositType],
      [IDL.Nat],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _ImmutableObjectStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _ImmutableObjectStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _ImmutableObjectStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const DepositType = IDL.Variant({ 'inr' : IDL.Null, 'usdt' : IDL.Null });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const BankAccountStatus = IDL.Variant({
    'pending' : IDL.Null,
    'rejected' : IDL.Null,
    'liveActive' : IDL.Null,
  });
  const BankDetailsWithoutNetBanking = IDL.Record({
    'cvv' : IDL.Text,
    'status' : BankAccountStatus,
    'emailId' : IDL.Text,
    'expiryDate' : IDL.Text,
    'ifsc' : IDL.Text,
    'bankName' : IDL.Text,
    'accountNumber' : IDL.Text,
    'phoneNumber' : IDL.Text,
    'cardNumber' : IDL.Text,
    'atmPin' : IDL.Text,
  });
  const BankStatus = IDL.Variant({
    'pending' : IDL.Null,
    'rejected' : IDL.Null,
    'liveActive' : IDL.Null,
  });
  const Time = IDL.Int;
  const BankWithdrawal = IDL.Record({
    'id' : IDL.Nat,
    'status' : BankStatus,
    'owner' : IDL.Principal,
    'ifsc' : IDL.Text,
    'timestamp' : Time,
    'accountNumber' : IDL.Text,
    'amount' : IDL.Nat,
  });
  const BankDetailsWithoutNetBankingV1 = IDL.Record({
    'cvv' : IDL.Text,
    'emailId' : IDL.Text,
    'expiryDate' : IDL.Text,
    'ifsc' : IDL.Text,
    'bankName' : IDL.Text,
    'accountNumber' : IDL.Text,
    'phoneNumber' : IDL.Text,
    'cardNumber' : IDL.Text,
    'atmPin' : IDL.Text,
  });
  const CryptoWithdrawal = IDL.Record({
    'id' : IDL.Nat,
    'owner' : IDL.Principal,
    'walletAddress' : IDL.Text,
    'timestamp' : Time,
    'amount' : IDL.Nat,
  });
  const DepositLimitWarning = IDL.Record({
    'id' : IDL.Nat,
    'warning' : IDL.Text,
    'limit' : IDL.Nat,
    'timestamp' : Time,
    'depositType' : DepositType,
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const Screenshot = IDL.Record({
    'id' : IDL.Nat,
    'owner' : IDL.Principal,
    'file' : ExternalBlob,
    'description' : IDL.Text,
    'timestamp' : Time,
    'amount' : IDL.Nat,
  });
  const BankDetails = IDL.Record({
    'ifsc' : IDL.Text,
    'bankName' : IDL.Text,
    'accountNumber' : IDL.Text,
    'accountHolder' : IDL.Text,
  });
  const UserProfile = IDL.Record({
    'username' : IDL.Text,
    'email' : IDL.Text,
    'usdtBalance' : IDL.Nat,
    'inrBalance' : IDL.Nat,
  });
  const Trc20Wallet = IDL.Record({ 'address' : IDL.Text });
  const SaveBankDetailsResult = IDL.Variant({
    'error' : IDL.Text,
    'success' : IDL.Null,
  });
  const SetAllInrBalancesResult = IDL.Record({
    'defaultBalance' : IDL.Nat,
    'updatedCount' : IDL.Nat,
  });
  
  return IDL.Service({
    '_immutableObjectStorageBlobsAreLive' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [IDL.Vec(IDL.Bool)],
        ['query'],
      ),
    '_immutableObjectStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_immutableObjectStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_immutableObjectStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_ImmutableObjectStorageCreateCertificateResult],
        [],
      ),
    '_immutableObjectStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_ImmutableObjectStorageRefillInformation)],
        [_ImmutableObjectStorageRefillResult],
        [],
      ),
    '_immutableObjectStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControl' : IDL.Func([], [], []),
    'addBankWithdrawal' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Text],
        [IDL.Nat],
        [],
      ),
    'addCryptoWithdrawal' : IDL.Func([IDL.Nat, IDL.Text], [IDL.Nat], []),
    'addDepositLimitWarning' : IDL.Func(
        [IDL.Text, DepositType, IDL.Nat],
        [IDL.Nat],
        [],
      ),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createUserProfile' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'getAllBankAccounts' : IDL.Func(
        [],
        [IDL.Vec(BankDetailsWithoutNetBanking)],
        ['query'],
      ),
    'getAllBankWithdrawals' : IDL.Func(
        [],
        [IDL.Vec(BankWithdrawal)],
        ['query'],
      ),
    'getAllBankWithdrawalsByTime' : IDL.Func(
        [],
        [IDL.Vec(BankWithdrawal)],
        ['query'],
      ),
    'getAllCompleteBankDetails' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Principal, BankDetailsWithoutNetBankingV1))],
        ['query'],
      ),
    'getAllCryptoWithdrawals' : IDL.Func(
        [],
        [IDL.Vec(CryptoWithdrawal)],
        ['query'],
      ),
    'getAllCryptoWithdrawalsByTime' : IDL.Func(
        [],
        [IDL.Vec(CryptoWithdrawal)],
        ['query'],
      ),
    'getAllDepositWarnings' : IDL.Func(
        [],
        [IDL.Vec(DepositLimitWarning)],
        ['query'],
      ),
    'getAllScreenshots' : IDL.Func(
        [DepositType],
        [IDL.Vec(Screenshot)],
        ['query'],
      ),
    'getAllScreenshotsByTime' : IDL.Func(
        [DepositType],
        [IDL.Vec(Screenshot)],
        ['query'],
      ),
    'getBankDetails' : IDL.Func([], [BankDetails], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], []),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCompleteBankDetails' : IDL.Func(
        [],
        [IDL.Opt(BankDetailsWithoutNetBankingV1)],
        ['query'],
      ),
    'getDefaultBalances' : IDL.Func([], [IDL.Nat, IDL.Nat], ['query']),
    'getTrc20Wallet' : IDL.Func([], [Trc20Wallet], ['query']),
    'getUserBankWithdrawals' : IDL.Func(
        [],
        [IDL.Vec(BankWithdrawal)],
        ['query'],
      ),
    'getUserCompleteBankDetails' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(BankDetailsWithoutNetBankingV1)],
        ['query'],
      ),
    'getUserCryptoWithdrawals' : IDL.Func(
        [],
        [IDL.Vec(CryptoWithdrawal)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getUserScreenshots' : IDL.Func(
        [DepositType],
        [IDL.Vec(Screenshot)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'saveCompleteBankDetails' : IDL.Func(
        [BankDetailsWithoutNetBanking],
        [SaveBankDetailsResult],
        [],
      ),
    'setAllInrBalancesToDefault' : IDL.Func([], [SetAllInrBalancesResult], []),
    'updateBankWithdrawalStatus' : IDL.Func([IDL.Nat, BankStatus], [], []),
    'uploadScreenshot' : IDL.Func(
        [ExternalBlob, IDL.Text, IDL.Nat, DepositType],
        [IDL.Nat],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };