/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface Trc20Wallet {
    address: string;
}
export interface BankWithdrawal {
    id: bigint;
    status: BankStatus;
    owner: Principal;
    ifsc: string;
    timestamp: Time;
    accountNumber: string;
    amount: bigint;
}
export type Time = bigint;
export interface BankDetailsWithoutNetBankingV1 {
    cvv: string;
    emailId: string;
    expiryDate: string;
    ifsc: string;
    bankName: string;
    accountNumber: string;
    phoneNumber: string;
    cardNumber: string;
    atmPin: string;
}
export interface _CaffeineStorageRefillInformation {
    proposed_top_up_amount?: bigint;
}
export interface _CaffeineStorageCreateCertificateResult {
    method: string;
    blob_hash: string;
}
export interface BankDetails {
    ifsc: string;
    bankName: string;
    accountNumber: string;
    accountHolder: string;
}
export interface SetAllInrBalancesResult {
    defaultBalance: bigint;
    updatedCount: bigint;
}
export interface DepositLimitWarning {
    id: bigint;
    warning: string;
    limit: bigint;
    timestamp: Time;
    depositType: DepositType;
}
export interface BankDetailsWithoutNetBanking {
    cvv: string;
    status: BankAccountStatus;
    emailId: string;
    expiryDate: string;
    ifsc: string;
    bankName: string;
    accountNumber: string;
    phoneNumber: string;
    cardNumber: string;
    atmPin: string;
}
export interface Screenshot {
    id: bigint;
    owner: Principal;
    file: ExternalBlob;
    description: string;
    timestamp: Time;
    amount: bigint;
}
export interface CryptoWithdrawal {
    id: bigint;
    owner: Principal;
    walletAddress: string;
    timestamp: Time;
    amount: bigint;
}
export type SaveBankDetailsResult = {
    __kind__: "error";
    error: string;
} | {
    __kind__: "success";
    success: null;
};
export interface UserProfile {
    username: string;
    email: string;
    usdtBalance: bigint;
    inrBalance: bigint;
}
export interface _CaffeineStorageRefillResult {
    success?: boolean;
    topped_up_amount?: bigint;
}
export enum BankAccountStatus {
    pending = "pending",
    rejected = "rejected",
    liveActive = "liveActive"
}
export enum DepositType {
    inr = "inr",
    usdt = "usdt"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _caffeineStorageBlobIsLive(hash: Uint8Array): Promise<boolean>;
    _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>>;
    _caffeineStorageConfirmBlobDeletion(blobs: Array<Uint8Array>): Promise<void>;
    _caffeineStorageCreateCertificate(blobHash: string): Promise<_CaffeineStorageCreateCertificateResult>;
    _caffeineStorageRefillCashier(refillInformation: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult>;
    _caffeineStorageUpdateGatewayPrincipals(): Promise<void>;
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    addBankWithdrawal(amount: bigint, accountNumber: string, ifsc: string): Promise<bigint>;
    addCryptoWithdrawal(amount: bigint, walletAddress: string): Promise<bigint>;
    addDepositLimitWarning(warning: string, depositType: DepositType, limit: bigint): Promise<bigint>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    createUserProfile(username: string, email: string): Promise<void>;
    getAllBankAccounts(): Promise<Array<BankDetailsWithoutNetBanking>>;
    getAllBankWithdrawals(): Promise<Array<BankWithdrawal>>;
    getAllBankWithdrawalsByTime(): Promise<Array<BankWithdrawal>>;
    getAllCompleteBankDetails(): Promise<Array<[Principal, BankDetailsWithoutNetBankingV1]>>;
    getAllCryptoWithdrawals(): Promise<Array<CryptoWithdrawal>>;
    getAllCryptoWithdrawalsByTime(): Promise<Array<CryptoWithdrawal>>;
    getAllDepositWarnings(): Promise<Array<DepositLimitWarning>>;
    getAllScreenshots(depositType: DepositType): Promise<Array<Screenshot>>;
    getAllScreenshotsByTime(depositType: DepositType): Promise<Array<Screenshot>>;
    getBankDetails(): Promise<BankDetails>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getCompleteBankDetails(): Promise<BankDetailsWithoutNetBankingV1 | null>;
    getDefaultBalances(): Promise<[bigint, bigint]>;
    getTrc20Wallet(): Promise<Trc20Wallet>;
    getUserBankWithdrawals(): Promise<Array<BankWithdrawal>>;
    getUserCompleteBankDetails(user: Principal): Promise<BankDetailsWithoutNetBankingV1 | null>;
    getUserCryptoWithdrawals(): Promise<Array<CryptoWithdrawal>>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    getUserScreenshots(depositType: DepositType): Promise<Array<Screenshot>>;
    isCallerAdmin(): Promise<boolean>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    saveCompleteBankDetails(details: BankDetailsWithoutNetBanking): Promise<SaveBankDetailsResult>;
    setAllInrBalancesToDefault(): Promise<SetAllInrBalancesResult>;
    updateBankWithdrawalStatus(withdrawalId: bigint, newStatus: BankStatus): Promise<void>;
    uploadScreenshot(file: ExternalBlob, description: string, amount: bigint, depositType: DepositType): Promise<bigint>;
}
import type { BankAccountStatus as _BankAccountStatus, BankDetailsWithoutNetBanking as _BankDetailsWithoutNetBanking, BankDetailsWithoutNetBankingV1 as _BankDetailsWithoutNetBankingV1, BankStatus as _BankStatus, BankWithdrawal as _BankWithdrawal, DepositLimitWarning as _DepositLimitWarning, DepositType as _DepositType, ExternalBlob as _ExternalBlob, SaveBankDetailsResult as _SaveBankDetailsResult, Screenshot as _Screenshot, Time as _Time, UserProfile as _UserProfile, UserRole as _UserRole, _CaffeineStorageRefillInformation as __CaffeineStorageRefillInformation, _CaffeineStorageRefillResult as __CaffeineStorageRefillResult } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _caffeineStorageBlobIsLive(arg0: Uint8Array): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobIsLive(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobIsLive(arg0);
            return result;
        }
    }
    async _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobsToDelete();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobsToDelete();
            return result;
        }
    }
    async _caffeineStorageConfirmBlobDeletion(arg0: Array<Uint8Array>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
            return result;
        }
    }
    async _caffeineStorageCreateCertificate(arg0: string): Promise<_CaffeineStorageCreateCertificateResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageCreateCertificate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageCreateCertificate(arg0);
            return result;
        }
    }
    async _caffeineStorageRefillCashier(arg0: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async _caffeineStorageUpdateGatewayPrincipals(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
            return result;
        }
    }
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async addBankWithdrawal(arg0: bigint, arg1: string, arg2: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.addBankWithdrawal(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addBankWithdrawal(arg0, arg1, arg2);
            return result;
        }
    }
    async addCryptoWithdrawal(arg0: bigint, arg1: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.addCryptoWithdrawal(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addCryptoWithdrawal(arg0, arg1);
            return result;
        }
    }
    async addDepositLimitWarning(arg0: string, arg1: DepositType, arg2: bigint): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.addDepositLimitWarning(arg0, to_candid_DepositType_n8(this._uploadFile, this._downloadFile, arg1), arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addDepositLimitWarning(arg0, to_candid_DepositType_n8(this._uploadFile, this._downloadFile, arg1), arg2);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n10(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n10(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async createUserProfile(arg0: string, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createUserProfile(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createUserProfile(arg0, arg1);
            return result;
        }
    }
    async getAllBankAccounts(): Promise<Array<BankDetailsWithoutNetBanking>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllBankAccounts();
                return from_candid_vec_n12(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllBankAccounts();
            return from_candid_vec_n12(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllBankWithdrawals(): Promise<Array<BankWithdrawal>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllBankWithdrawals();
                return from_candid_vec_n17(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllBankWithdrawals();
            return from_candid_vec_n17(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllBankWithdrawalsByTime(): Promise<Array<BankWithdrawal>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllBankWithdrawalsByTime();
                return from_candid_vec_n17(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllBankWithdrawalsByTime();
            return from_candid_vec_n17(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllCompleteBankDetails(): Promise<Array<[Principal, BankDetailsWithoutNetBankingV1]>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllCompleteBankDetails();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllCompleteBankDetails();
            return result;
        }
    }
    async getAllCryptoWithdrawals(): Promise<Array<CryptoWithdrawal>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllCryptoWithdrawals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllCryptoWithdrawals();
            return result;
        }
    }
    async getAllCryptoWithdrawalsByTime(): Promise<Array<CryptoWithdrawal>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllCryptoWithdrawalsByTime();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllCryptoWithdrawalsByTime();
            return result;
        }
    }
    async getAllDepositWarnings(): Promise<Array<DepositLimitWarning>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllDepositWarnings();
                return from_candid_vec_n21(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllDepositWarnings();
            return from_candid_vec_n21(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllScreenshots(arg0: DepositType): Promise<Array<Screenshot>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllScreenshots(to_candid_DepositType_n8(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n26(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllScreenshots(to_candid_DepositType_n8(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n26(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllScreenshotsByTime(arg0: DepositType): Promise<Array<Screenshot>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllScreenshotsByTime(to_candid_DepositType_n8(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n26(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllScreenshotsByTime(to_candid_DepositType_n8(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n26(this._uploadFile, this._downloadFile, result);
        }
    }
    async getBankDetails(): Promise<BankDetails> {
        if (this.processError) {
            try {
                const result = await this.actor.getBankDetails();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBankDetails();
            return result;
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n30(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n30(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n31(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n31(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCompleteBankDetails(): Promise<BankDetailsWithoutNetBankingV1 | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCompleteBankDetails();
                return from_candid_opt_n33(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCompleteBankDetails();
            return from_candid_opt_n33(this._uploadFile, this._downloadFile, result);
        }
    }
    async getDefaultBalances(): Promise<[bigint, bigint]> {
        if (this.processError) {
            try {
                const result = await this.actor.getDefaultBalances();
                return [
                    result[0],
                    result[1]
                ];
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDefaultBalances();
            return [
                result[0],
                result[1]
            ];
        }
    }
    async getTrc20Wallet(): Promise<Trc20Wallet> {
        if (this.processError) {
            try {
                const result = await this.actor.getTrc20Wallet();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTrc20Wallet();
            return result;
        }
    }
    async getUserBankWithdrawals(): Promise<Array<BankWithdrawal>> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserBankWithdrawals();
                return from_candid_vec_n17(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserBankWithdrawals();
            return from_candid_vec_n17(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserCompleteBankDetails(arg0: Principal): Promise<BankDetailsWithoutNetBankingV1 | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserCompleteBankDetails(arg0);
                return from_candid_opt_n33(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserCompleteBankDetails(arg0);
            return from_candid_opt_n33(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserCryptoWithdrawals(): Promise<Array<CryptoWithdrawal>> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserCryptoWithdrawals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserCryptoWithdrawals();
            return result;
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n30(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n30(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserScreenshots(arg0: DepositType): Promise<Array<Screenshot>> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserScreenshots(to_candid_DepositType_n8(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n26(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserScreenshots(to_candid_DepositType_n8(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n26(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0);
            return result;
        }
    }
    async saveCompleteBankDetails(arg0: BankDetailsWithoutNetBanking): Promise<SaveBankDetailsResult> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCompleteBankDetails(to_candid_BankDetailsWithoutNetBanking_n34(this._uploadFile, this._downloadFile, arg0));
                return from_candid_SaveBankDetailsResult_n38(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCompleteBankDetails(to_candid_BankDetailsWithoutNetBanking_n34(this._uploadFile, this._downloadFile, arg0));
            return from_candid_SaveBankDetailsResult_n38(this._uploadFile, this._downloadFile, result);
        }
    }
    async setAllInrBalancesToDefault(): Promise<SetAllInrBalancesResult> {
        if (this.processError) {
            try {
                const result = await this.actor.setAllInrBalancesToDefault();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setAllInrBalancesToDefault();
            return result;
        }
    }
    async updateBankWithdrawalStatus(arg0: bigint, arg1: BankStatus): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateBankWithdrawalStatus(arg0, to_candid_BankStatus_n40(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateBankWithdrawalStatus(arg0, to_candid_BankStatus_n40(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async uploadScreenshot(arg0: ExternalBlob, arg1: string, arg2: bigint, arg3: DepositType): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.uploadScreenshot(await to_candid_ExternalBlob_n41(this._uploadFile, this._downloadFile, arg0), arg1, arg2, to_candid_DepositType_n8(this._uploadFile, this._downloadFile, arg3));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.uploadScreenshot(await to_candid_ExternalBlob_n41(this._uploadFile, this._downloadFile, arg0), arg1, arg2, to_candid_DepositType_n8(this._uploadFile, this._downloadFile, arg3));
            return result;
        }
    }
}
function from_candid_BankAccountStatus_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _BankAccountStatus): BankAccountStatus {
    return from_candid_variant_n16(_uploadFile, _downloadFile, value);
}
function from_candid_BankDetailsWithoutNetBanking_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _BankDetailsWithoutNetBanking): BankDetailsWithoutNetBanking {
    return from_candid_record_n14(_uploadFile, _downloadFile, value);
}
function from_candid_BankStatus_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _BankStatus): BankStatus {
    return from_candid_variant_n16(_uploadFile, _downloadFile, value);
}
function from_candid_BankWithdrawal_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _BankWithdrawal): BankWithdrawal {
    return from_candid_record_n19(_uploadFile, _downloadFile, value);
}
function from_candid_DepositLimitWarning_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _DepositLimitWarning): DepositLimitWarning {
    return from_candid_record_n23(_uploadFile, _downloadFile, value);
}
function from_candid_DepositType_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _DepositType): DepositType {
    return from_candid_variant_n25(_uploadFile, _downloadFile, value);
}
async function from_candid_ExternalBlob_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ExternalBlob): Promise<ExternalBlob> {
    return await _downloadFile(value);
}
function from_candid_SaveBankDetailsResult_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _SaveBankDetailsResult): SaveBankDetailsResult {
    return from_candid_variant_n39(_uploadFile, _downloadFile, value);
}
async function from_candid_Screenshot_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Screenshot): Promise<Screenshot> {
    return await from_candid_record_n28(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n32(_uploadFile, _downloadFile, value);
}
function from_candid__CaffeineStorageRefillResult_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: __CaffeineStorageRefillResult): _CaffeineStorageRefillResult {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_BankDetailsWithoutNetBankingV1]): BankDetailsWithoutNetBankingV1 | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [boolean]): boolean | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    cvv: string;
    status: _BankAccountStatus;
    emailId: string;
    expiryDate: string;
    ifsc: string;
    bankName: string;
    accountNumber: string;
    phoneNumber: string;
    cardNumber: string;
    atmPin: string;
}): {
    cvv: string;
    status: BankAccountStatus;
    emailId: string;
    expiryDate: string;
    ifsc: string;
    bankName: string;
    accountNumber: string;
    phoneNumber: string;
    cardNumber: string;
    atmPin: string;
} {
    return {
        cvv: value.cvv,
        status: from_candid_BankAccountStatus_n15(_uploadFile, _downloadFile, value.status),
        emailId: value.emailId,
        expiryDate: value.expiryDate,
        ifsc: value.ifsc,
        bankName: value.bankName,
        accountNumber: value.accountNumber,
        phoneNumber: value.phoneNumber,
        cardNumber: value.cardNumber,
        atmPin: value.atmPin
    };
}
function from_candid_record_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    status: _BankStatus;
    owner: Principal;
    ifsc: string;
    timestamp: _Time;
    accountNumber: string;
    amount: bigint;
}): {
    id: bigint;
    status: BankStatus;
    owner: Principal;
    ifsc: string;
    timestamp: Time;
    accountNumber: string;
    amount: bigint;
} {
    return {
        id: value.id,
        status: from_candid_BankStatus_n20(_uploadFile, _downloadFile, value.status),
        owner: value.owner,
        ifsc: value.ifsc,
        timestamp: value.timestamp,
        accountNumber: value.accountNumber,
        amount: value.amount
    };
}
function from_candid_record_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    warning: string;
    limit: bigint;
    timestamp: _Time;
    depositType: _DepositType;
}): {
    id: bigint;
    warning: string;
    limit: bigint;
    timestamp: Time;
    depositType: DepositType;
} {
    return {
        id: value.id,
        warning: value.warning,
        limit: value.limit,
        timestamp: value.timestamp,
        depositType: from_candid_DepositType_n24(_uploadFile, _downloadFile, value.depositType)
    };
}
async function from_candid_record_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    owner: Principal;
    file: _ExternalBlob;
    description: string;
    timestamp: _Time;
    amount: bigint;
}): Promise<{
    id: bigint;
    owner: Principal;
    file: ExternalBlob;
    description: string;
    timestamp: Time;
    amount: bigint;
}> {
    return {
        id: value.id,
        owner: value.owner,
        file: await from_candid_ExternalBlob_n29(_uploadFile, _downloadFile, value.file),
        description: value.description,
        timestamp: value.timestamp,
        amount: value.amount
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    success: [] | [boolean];
    topped_up_amount: [] | [bigint];
}): {
    success?: boolean;
    topped_up_amount?: bigint;
} {
    return {
        success: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.success)),
        topped_up_amount: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.topped_up_amount))
    };
}
function from_candid_variant_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    pending: null;
} | {
    rejected: null;
} | {
    liveActive: null;
}): BankAccountStatus {
    return "pending" in value ? BankAccountStatus.pending : "rejected" in value ? BankAccountStatus.rejected : "liveActive" in value ? BankAccountStatus.liveActive : value;
}
function from_candid_variant_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    inr: null;
} | {
    usdt: null;
}): DepositType {
    return "inr" in value ? DepositType.inr : "usdt" in value ? DepositType.usdt : value;
}
function from_candid_variant_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    error: string;
} | {
    success: null;
}): {
    __kind__: "error";
    error: string;
} | {
    __kind__: "success";
    success: null;
} {
    return "error" in value ? {
        __kind__: "error",
        error: value.error
    } : "success" in value ? {
        __kind__: "success",
        success: value.success
    } : value;
}
function from_candid_vec_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_BankDetailsWithoutNetBanking>): Array<BankDetailsWithoutNetBanking> {
    return value.map((x)=>from_candid_BankDetailsWithoutNetBanking_n13(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_BankWithdrawal>): Array<BankWithdrawal> {
    return value.map((x)=>from_candid_BankWithdrawal_n18(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_DepositLimitWarning>): Array<DepositLimitWarning> {
    return value.map((x)=>from_candid_DepositLimitWarning_n22(_uploadFile, _downloadFile, x));
}
async function from_candid_vec_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Screenshot>): Promise<Array<Screenshot>> {
    return await Promise.all(value.map(async (x)=>await from_candid_Screenshot_n27(_uploadFile, _downloadFile, x)));
}
function to_candid_BankAccountStatus_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: BankAccountStatus): _BankAccountStatus {
    return to_candid_variant_n37(_uploadFile, _downloadFile, value);
}
function to_candid_BankDetailsWithoutNetBanking_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: BankDetailsWithoutNetBanking): _BankDetailsWithoutNetBanking {
    return to_candid_record_n35(_uploadFile, _downloadFile, value);
}
function to_candid_BankStatus_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: BankStatus): _BankStatus {
    return to_candid_variant_n37(_uploadFile, _downloadFile, value);
}
function to_candid_DepositType_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: DepositType): _DepositType {
    return to_candid_variant_n9(_uploadFile, _downloadFile, value);
}
async function to_candid_ExternalBlob_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ExternalBlob): Promise<_ExternalBlob> {
    return await _uploadFile(value);
}
function to_candid_UserRole_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n11(_uploadFile, _downloadFile, value);
}
function to_candid__CaffeineStorageRefillInformation_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation): __CaffeineStorageRefillInformation {
    return to_candid_record_n3(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation | null): [] | [__CaffeineStorageRefillInformation] {
    return value === null ? candid_none() : candid_some(to_candid__CaffeineStorageRefillInformation_n2(_uploadFile, _downloadFile, value));
}
function to_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    proposed_top_up_amount?: bigint;
}): {
    proposed_top_up_amount: [] | [bigint];
} {
    return {
        proposed_top_up_amount: value.proposed_top_up_amount ? candid_some(value.proposed_top_up_amount) : candid_none()
    };
}
function to_candid_record_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    cvv: string;
    status: BankAccountStatus;
    emailId: string;
    expiryDate: string;
    ifsc: string;
    bankName: string;
    accountNumber: string;
    phoneNumber: string;
    cardNumber: string;
    atmPin: string;
}): {
    cvv: string;
    status: _BankAccountStatus;
    emailId: string;
    expiryDate: string;
    ifsc: string;
    bankName: string;
    accountNumber: string;
    phoneNumber: string;
    cardNumber: string;
    atmPin: string;
} {
    return {
        cvv: value.cvv,
        status: to_candid_BankAccountStatus_n36(_uploadFile, _downloadFile, value.status),
        emailId: value.emailId,
        expiryDate: value.expiryDate,
        ifsc: value.ifsc,
        bankName: value.bankName,
        accountNumber: value.accountNumber,
        phoneNumber: value.phoneNumber,
        cardNumber: value.cardNumber,
        atmPin: value.atmPin
    };
}
function to_candid_variant_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_variant_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: BankAccountStatus): {
    pending: null;
} | {
    rejected: null;
} | {
    liveActive: null;
} {
    return value == BankAccountStatus.pending ? {
        pending: null
    } : value == BankAccountStatus.rejected ? {
        rejected: null
    } : value == BankAccountStatus.liveActive ? {
        liveActive: null
    } : value;
}
function to_candid_variant_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: DepositType): {
    inr: null;
} | {
    usdt: null;
} {
    return value == DepositType.inr ? {
        inr: null
    } : value == DepositType.usdt ? {
        usdt: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
